/*
 * ADC_prg.c
 *
 *  Created on: Feb 15, 2020
 *      Author: Dan
 */
#include"../Lib/Std_types.h"
#include"../Lib/Bit_math.h"
#include<avr/io.h>
#include"ADC_int.h"




void Adc_vidInit(void){

	CLR_BIT(ADMUX,7);	//7TH BIT REFS1	AVCC WITH EXTERNAL
	SET_BIT(ADMUX,6);	//6TH BIT REFS0 CAPACITOR AT AREF pin
	CLR_BIT(ADMUX,5);	//RIGHT ADJUSTED IN ADLAR BIT
	CLR_BIT(ADMUX,4);	//ADC CHANNEL 0
	CLR_BIT(ADMUX,3);	//ADC CHANNEL 0
	CLR_BIT(ADMUX,2);	//ADC CHANNEL 0	page 212,213
	CLR_BIT(ADMUX,1);	//ADC CHANNEL 0
	CLR_BIT(ADMUX,0);	//ADC CHANNEL 0

	SET_BIT(ADCSRA,7);	//ENABLE ADC ADEN
	CLR_BIT(ADCSRA,6);	//ADSC ADC START CONVERSION DISABLED
	CLR_BIT(ADCSRA,5);	//ADC AUTO TRIGGER ADATE DISABLED
	SET_BIT(ADCSRA,4);  //ADIF INTERRUPT FLAG CLEARED BY WRITING ONE TO IT
	CLR_BIT(ADCSRA,3);  //ADIE ADC INTERRUPT ENABLE CLEARED

	CLR_BIT(ADCSRA,2);  //ADPS2		PRESCALER SELECTED TO 8 MHZ
	SET_BIT(ADCSRA,1);	//ADPS1		PRESCALER SELECTED TO 8 MHZ
	CLR_BIT(ADCSRA,0);	//ADPS0		PRESCALER SELECTED TO 8 MHZ
}


u16 Adc_u16GetResult(u8 Chnl_Id){
	u16 result=0;
	ADMUX&=0b11100000;	//CLEAR 5 MUX BITS BEFORE SELECTING CHANNEL
	ADMUX|=(Chnl_Id&0b00011111);		//XOR-ING WITH OUTER 5 MUX BITS TO SELECT CHANNEL
	SET_BIT(ADCSRA,6); //START ADC
	while(GET_BIT(ADCSRA,4)==0); //CHECK FOR ADIF FLAG
	SET_BIT(ADCSRA,4);		//INTERRUPT FLAG CLEARED BY WRITING ONE
	result=ADCL;			//RESULT CONTAINING THE LOWER 8 BITS OF THE ADC 10 BIT CHANNEL
	result|=(ADCH<<8);		//RESULT CONTAINGING THE HIGHER BITS OF THE ADC 10 BIT CHANNEL BY XOR-ING THE (LEFT SHIFTED BY 8 BITS)
	return result;
}
